update

diff --git a/src/jenkins/Jenkinsfile.ssh b/src/jenkins/Jenkinsfile.ssh
--- a/src/jenkins/Jenkinsfile.ssh
+++ b/src/jenkins/Jenkinsfile.ssh
@@ -20,17 +20,21 @@ pipeline {
               ]
             }
           ]'
-          
-          echo $sshRule
-                
-          output=$(aws ec2 authorize-security-group-ingress --group-id sg-0bf8de7b0ac4b3f40 --ip-permissions "$sshRule" 2>&1)
-          echo "Added successfully"
-          exit_status=$?
-          if [[ $exit_status -ne 0 ]]; then 
-            echo "Error: $output"
-            exit $exit_status
-          else
-            
+
+          errorFlag=0
+          echo "Adding"
+          {
+            aws ec2 authorize-security-group-ingress --group-id sg-0bf8de7b0ac4b3f40 --ip-permissions "$sshRule"
+            if [[$? -eq 0 ]]; then
+              echo "Successfully"
+            else
+              errorFlag=1
+            fi
+          } || {}
+
+          if [[ $errorFlag -eq 1 ]]; then 
+            echo "Error found"
+            exit 1            
           fi
         '''
       }
