update

diff --git a/src/jenkins/Jenkinsfile.ssh b/src/jenkins/Jenkinsfile.ssh
--- a/src/jenkins/Jenkinsfile.ssh
+++ b/src/jenkins/Jenkinsfile.ssh
@@ -25,12 +25,13 @@ pipeline {
           
           echo $sshRule
                 
-          try {
-            aws ec2 authorize-security-group-ingress --group-id sg-0bf8de7b0ac4b3f40 --ip-permissions "$sshRule"
-            echo "Adding successfully"
-          } catch (Exception  e) {
-            echo "Error occurred: ${e.message}"
-          }
+          output=$(aws ec2 authorize-security-group-ingress --group-id sg-0bf8de7b0ac4b3f40 --ip-permissions "$sshRule" 2>&1)
+          exit_status=$?
+          if [[ $exit_status -eq 0 ]]; then 
+            echo "Added successfully"
+          else
+            echo "Error: $output"
+          fi
 
         '''
       }
